/*
 * Copyright (c) 2026 Rudra Joshi
 * SPDX-License-Identifier: Apache-2.0
 *
 * Tiny Tapeout wrapper for the Bambu HLS version of GIFT-64-128
 * (gift64_top.v, generated by Bambu 2024.10 from hls/gift64_hls_opt.c,
 * configuration C: -O3 --rom-duplication). Same pins and register map as the
 * hand-written design on the main branch, so the same cocotb test applies.
 *
 * Pins:
 *   ui_in[4:0]   byte address
 *   ui_in[7]     write strobe (synchronised in strobe_sync.v)
 *   uio_in[7:0]  write data
 *   uo_out[7:0]  read data at the selected address (registered)
 *
 * Address map:
 *   0x00..0x0F  KEY    key[127:120] at 0x00 ... key[7:0] at 0x0F   (R/W)
 *   0x10..0x17  STATE  write: plaintext, pt[63:56] at 0x10 ...       (R/W)
 *                      read:  plaintext before start, ciphertext after done
 *   0x18        write: bit 0 = 1 starts an encryption (ignored while busy)
 *               read:  bit 0 = busy, bit 1 = done
 *   0x19        ID, reads 0x47 (ASCII 'G')
 *   0x1A..0x1F  read 0, writes ignored
 *
 * Unlike the hand-written core, the HLS core has no storage of its own for
 * the key and plaintext, so this wrapper holds them (192 flip-flops) and
 * feeds them to the core's 64-bit ports. While busy, writes are ignored and
 * KEY and STATE reads return 0. The key register is never changed by an
 * encryption.
 */

`default_nettype none

module tt_um_rj_gift (
    input  wire [7:0] ui_in,    // Dedicated inputs
    output wire [7:0] uo_out,   // Dedicated outputs
    input  wire [7:0] uio_in,   // IOs: Input path
    output wire [7:0] uio_out,  // IOs: Output path
    output wire [7:0] uio_oe,   // IOs: Enable path (active high: 0=input, 1=output)
    input  wire       ena,      // always 1 when the design is powered, so you can ignore it
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);

  wire [4:0] addr  = ui_in[4:0];
  wire [7:0] wdata = uio_in;

  wire wr_pulse;
  strobe_sync u_sync (.clk(clk), .rst_n(rst_n), .strobe_in(ui_in[7]), .pulse(wr_pulse));

  wire start       = wr_pulse & (addr == 5'h18) & wdata[0];
  wire state_write = wr_pulse & (addr[4:3] == 2'b10);       // 0x10..0x17

  reg  [127:0] key;     // no reset: written before use
  reg  [63:0]  state;   // no reset: written before use
  reg          busy, done, go;

  wire         core_done;
  wire [63:0]  core_ct;

  // Bambu core: synchronous active-low reset, one-cycle start and done pulses.
  gift64_top u_hls (
      .clock(clk), .reset(rst_n),
      .start_port(go),
      .pt(state), .key_hi(key[127:64]), .key_lo(key[63:0]),
      .done_port(core_done), .return_port(core_ct)
  );

  // Control (reset)
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      busy <= 1'b0;
      done <= 1'b0;
      go   <= 1'b0;
    end else begin
      go <= 1'b0;
      if (start && !busy) begin
        busy <= 1'b1;
        done <= 1'b0;
        go   <= 1'b1;
      end else if (busy) begin
        if (core_done) begin
          busy <= 1'b0;
          done <= 1'b1;
        end
      end else if (state_write) begin
        done <= 1'b0;                    // new plaintext: old result gone
      end
    end
  end

  // Data registers (no reset)
  always @(posedge clk) begin
    if (busy) begin
      if (core_done) state <= core_ct;   // ciphertext replaces plaintext
    end else if (wr_pulse) begin
      case (addr)
      5'h00: key[127:120] <= wdata;
      5'h01: key[119:112] <= wdata;
      5'h02: key[111:104] <= wdata;
      5'h03: key[103:96] <= wdata;
      5'h04: key[95:88] <= wdata;
      5'h05: key[87:80] <= wdata;
      5'h06: key[79:72] <= wdata;
      5'h07: key[71:64] <= wdata;
      5'h08: key[63:56] <= wdata;
      5'h09: key[55:48] <= wdata;
      5'h0A: key[47:40] <= wdata;
      5'h0B: key[39:32] <= wdata;
      5'h0C: key[31:24] <= wdata;
      5'h0D: key[23:16] <= wdata;
      5'h0E: key[15:8] <= wdata;
      5'h0F: key[7:0] <= wdata;
      5'h10: state[63:56] <= wdata;
      5'h11: state[55:48] <= wdata;
      5'h12: state[47:40] <= wdata;
      5'h13: state[39:32] <= wdata;
      5'h14: state[31:24] <= wdata;
      5'h15: state[23:16] <= wdata;
      5'h16: state[15:8] <= wdata;
      5'h17: state[7:0] <= wdata;
      default: ;
      endcase
    end
  end

  reg [7:0] rdata;
  always @(*) begin
    case (addr)
      5'h00: rdata = key[127:120];
      5'h01: rdata = key[119:112];
      5'h02: rdata = key[111:104];
      5'h03: rdata = key[103:96];
      5'h04: rdata = key[95:88];
      5'h05: rdata = key[87:80];
      5'h06: rdata = key[79:72];
      5'h07: rdata = key[71:64];
      5'h08: rdata = key[63:56];
      5'h09: rdata = key[55:48];
      5'h0A: rdata = key[47:40];
      5'h0B: rdata = key[39:32];
      5'h0C: rdata = key[31:24];
      5'h0D: rdata = key[23:16];
      5'h0E: rdata = key[15:8];
      5'h0F: rdata = key[7:0];
      5'h10: rdata = state[63:56];
      5'h11: rdata = state[55:48];
      5'h12: rdata = state[47:40];
      5'h13: rdata = state[39:32];
      5'h14: rdata = state[31:24];
      5'h15: rdata = state[23:16];
      5'h16: rdata = state[15:8];
      5'h17: rdata = state[7:0];
      5'h18: rdata = {6'b000000, done, busy};  // status
      5'h19: rdata = 8'h47;                     // ID: ASCII 'G'
      default: rdata = 8'h00;                   // 0x1A to 0x1F: unused
    endcase
    if (busy && addr <= 5'h17)
      rdata = 8'h00;                            // hide values while busy
  end

  reg [7:0] rdata_q;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      rdata_q <= 8'h00;
    else
      rdata_q <= rdata;
  end

  assign uo_out  = rdata_q;
  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

  wire _unused = &{ena, ui_in[6:5], 1'b0};

endmodule
